db:
  image: mysql:5.6
  container_name: db
  environment:
    MYSQL_DATABASE: ceph
    MYSQL_ROOT_PASSWORD: "passwd"
backend:
  image: imaccloud/s3-api:0.2.0
  container_name: backend
  links:
    - db:db
  environment:
    ACCESS_KEY: "<RADOSGW_ADMIN_ACCESS_KEY>"
    SECERT_KEY: "<RADOSGW_ADMIN_SECERT_KEY>"
    S3_URL: "<RADOSGW_S3_URL>"
    ADMIN_ENRTYPOINT: "<RADOSGW_ADMIN_ENRTYPOINT>"
  ports:
    - 8080:80
frontend:
  image: imaccloud/s3-ui:0.2.0
  container_name: frontend
  environment:
    BACKEND_ADDRESS: "<S3_API_ADDRESS>"
  ports:
    - 80:3000
    -
