version: '2'
services:
  db:
    image: mysql:5.6
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD="<db_root_passwd>"
    ports:
      - 3306:3306
  backend:
    image: imaccloud/s3-api:0.1.0
    container_name: s3-api
    links:
      - db
    environment:
      - DB_HOST="<db_host>"
      - ACCESS_KEY="<access_key>"
      - SECERT_KEY="<secret_key>"
      - S3_URL="<s3_server_key>"
      - ADMIN_ENRTYPOINT="<admin_entrypoint>"
    ports:
      - 8080:80
  frontend:
    image: imaccloud/s3-ui:0.1.0
    container_name: frontend
    environment:
      - BACKEND_HOST="<backend_host>:8080"
    ports:
      - 80:3000
