db:
  image: mysql:5.6
  container_name: db
  environment:
    MYSQL_DATABASE: ceph
    MYSQL_ROOT_PASSWORD: r00tme
backend:
  image: imaccloud/s3-api:0.1.1
  container_name: backend
  links:
    - db:db
  environment:
    ACCESS_KEY: "<access_key>"
    SECERT_KEY: "<secert_key>"
    S3_URL: "<radosgw_s3_url>"
    ADMIN_ENRTYPOINT: "<radosgw_admin_entrypoint>"
  ports:
    - 8080:80
frontend:
  image: imaccloud/s3-ui:0.1.1
  container_name: frontend
  environment:
    BACKEND_ADDRESS: "192.168.99.100:8080"
  ports:
    - 80:3000
