---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-mysql-pvc
  labels:
    app: portal-mysql
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
