---
apiVersion: v1
kind: Service
metadata:
  name: portal-mysql
  labels:
    app: portal-mysql
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: portal-mysql
