---
apiVersion: v1
kind: Service
metadata:
  name: portal-api
  labels:
    app: portal-api
    daemon: api
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal-api
    daemon: api
