---
apiVersion: v1
kind: Service
metadata:
  name: portal-ui
  labels:
    app: portal-ui
    daemon: ui
spec:
  clusterIP: None
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: portal-ui
    daemon: ui
