---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: portal-ui
    daemon: ui
  name: portal-ui
spec:
  replicas: 1
  template:
    metadata:
      name: portal-ui
      labels:
        app: portal-ui
        daemon: ui
    spec:
      containers:
      - name: portal-ui
        image: inwinstack/s3-portal-ui:dev
        ports:
        - containerPort: 3000
        env:
        - name: API_HOST
          value: portal-api.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "1.0"
          limits:
            memory: "512Mi"
            cpu: "1.0"
